### PR TITLE
Expose metrics

### LINKED ISSUE #25: Expose metrics for better monitoring
## What

Currently, pvc-autoresizer does not expose any metrics.
In some situations such as #24, the process exits with an error.
This is not monitoring-friendly, so we want to add another method to report such events.
Metrics is the best for monitoring.

## How

- Expose the below metrics as a prometheus metrics.
  - pvcautoresizer_kubernetes_client_fail_total (namespace=pvcautoresizer, subsystem=kubernetes_client, name=fail_total)
    - counter that indicates how many API requests to kube-api server are failed.
  - pvcautoresizer_metrics_client_fail_total (namespace=pvcautoresizer, subsystem=metrics_client, name=fail_total)
    - counter that indicates how many API requests to metrics server(e.g. prometheus) are failed.
  - pvcautoresizer_success_loop_total (namespace=pvcautoresizer, subsystem=, name=success_loop_total)
    - counter that indicates how many volume expansion processing loops succeed.
  - pvcautoresizer_failed_loop_total (namespace=pvcautoresizer, subsystem=, name=failed_loop_total)
    - counter that indicates how many volume expansion processing loops are failed.
  - pvcautoresizer_loop_seconds_total (namespace=pvcautoresizer, subsystem=, name=loop_seconds_total)
    - counter that indicates the sum of seconds spent on volume expansion processing loops
- Do not exit when some error occurs

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

### PR DESCRIPTION
**Pull request by bells17**
resolve #25

### CODE REVIEW

File: metrics/metrics_client.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+	a.address = address
+}
+
+var (
+	metricsClientFailTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
+		Namespace: MetricsNamespace,
+		Subsystem: MetricsClientSubsystem,
+		Name:      MetricsClientFailTotalKey,
+		Help:      "counter that indicates how many API requests to metrics server(e.g. prometheus) are failed.",
+	}, []string{"namespace", "name"})
```
Comment (llamerada-jp) [inline metrics/metrics_client.go:37]: `namespace` and `name` labels are highly likely to conflict with other relabeled labels since it is too general. Would you add a prefix like `metrics_`?

File: metrics/resizer.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+func (a *loopSecondsTotalAdapter) Add(value float64) {
+	a.metric.Add(value)
+}
+
+var (
+	resizerSuccessLoopTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
+		Namespace: MetricsNamespace,
+		Name:      ResizerSuccessLoopTotalKey,
+		Help:      "counter that indicates how many volume expansion processing loops succeed.",
+	}, []string{"namespace", "name"})
```
Comment (llamerada-jp) [inline metrics/resizer.go:48]: `namespace` and `name` labels are highly likely to conflict with other relabeled labels since it is too general. Would you add a prefix like `pvc_`?

File: metrics/resizer.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+
+	resizerFailedLoopTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
+		Namespace: MetricsNamespace,
+		Name:      ResizerFailedLoopTotalKey,
+		Help:      "counter that indicates how many volume expansion processing loops are failed.",
+	}, []string{"namespace", "name"})
```
Comment (llamerada-jp) [inline metrics/resizer.go:54]: Same as my previous point.

File: metrics/metrics_client.go (hunk 1 above)
Comment (llamerada-jp) [reply metrics/metrics_client.go:37]: Correct my mistake, the label does not match the content.

File: runners/suite_test.go [hunk 4]
```diff
@@ -65,31 +68,40 @@ var _ = BeforeSuite(func(done Done) {
...
 	// +kubebuilder:scaffold:scheme
 
-	mgr, err := ctrl.NewManager(cfg, ctrl.Options{
-		Scheme: scheme,
+	m, err := ctrl.NewManager(cfg, ctrl.Options{
+		Scheme:             scheme,
+		MetricsBindAddress: ":8080",
 	})
 	Expect(err).ToNot(HaveOccurred())
+	mgr = &m
```
Comment (llamerada-jp) [inline runners/suite_test.go:76]: It looks no need to rename to `m`.

File: metrics/kubernetes_client.go [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+	a.metric.WithLabelValues(group, version, kind, verb).Inc()
+}
+
+var (
+	kubernetesClientFailTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
+		Namespace: MetricsNamespace,
+		Subsystem: KubernetesClientSubsystem,
+		Name:      KubernetesClientFailTotalKey,
+		Help:      "counter that indicates how many API requests to kube-api server are failed.",
+	}, []string{"group", "version", "kind", "verb"})
```
Comment (llamerada-jp) [inline metrics/kubernetes_client.go:32]: I think this metric doesn't ​needs to be labeled. Because, it is very rarely that only a part of APIs will be failed.

File: runners/metrics_client_test.go [hunk 6]
```diff
@@ -30,3 +32,29 @@ func (c *prometheusClientMock) setResponce(key types.NamespacedName, stats *Volu
 	}
 	c.stats[key] = stats
 }
+
+var _ = Describe("test prometheusClient", func() {
+	It("test metrics", func() {
+		c, err := NewPrometheusClient("http://noconnection")
```
Comment (toshipp) [inline runners/metrics_client_test.go:38]: I think this is not good. Would you make a fake server that returns always 404.
Ex. use `httptest.NewServer` and `http.NotFound`

File: runners/pvc_autoresizer_test.go [hunk 7]
```diff
@@ -176,6 +176,92 @@ var _ = Describe("test resizer", func() {
 				})
 			}
 		})
+
+		Context("metrics tests", func() {
+			It("should outout metrics", func() {
```
Comment (toshipp) [inline runners/pvc_autoresizer_test.go:181]: typo of output?

**Review by toshipp — CHANGES_REQUESTED** [review]

File: runners/client_wrapper_test.go [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+	"github.com/prometheus/common/expfmt"
+	"github.com/topolvm/pvc-autoresizer/client"
+	corev1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+)
+
+var _ = Describe("test clientWrapper", func() {
+	It("test metrics", func() {
+		m := *mgr
+		wrappedClient := client.NewClientWrapper(m.GetClient())
```
Comment (toshipp) [inline runners/client_wrapper_test.go:19]: I prefer using a mock client that always fails for NewClientWrapper.
Do you need to use real client?

File: metrics/kubernetes_client.go (hunk 5 above)
Comment (toshipp) [reply metrics/kubernetes_client.go:32]: I agree with your thought.

File: runners/metrics_client_test.go (hunk 6 above)
Comment (bells17) [reply runners/metrics_client_test.go]: fixed it.

File: runners/client_wrapper_test.go [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+			if m.Counter.Value == nil {
+				continue
+			}
+			value = int(*m.Counter.Value)
+		}
+		Expect(value).NotTo(Equal(0))
+	})
+})
+
+func getMetricsFamily() (map[string]*dto.MetricFamily, error) {
```
[the remark this answers is not in the document]
Comment (bells17) [reply runners/client_wrapper_test.go]: fixed it.

File: runners/pvc_autoresizer_test.go (hunk 7 above)
Comment (bells17) [reply runners/pvc_autoresizer_test.go]: fixed it.

File: metrics/kubernetes_client.go (hunk 5 above)
Comment (bells17) [reply metrics/kubernetes_client.go]: fixed it.

File: runners/suite_test.go (hunk 4 above)
Comment (bells17) [reply runners/suite_test.go]: fixed it.

File: runners/metrics_client_test.go [hunk 10]
```diff
@@ -35,7 +37,12 @@ func (c *prometheusClientMock) setResponce(key types.NamespacedName, stats *Volu
 
 var _ = Describe("test prometheusClient", func() {
 	It("test metrics", func() {
-		c, err := NewPrometheusClient("http://noconnection")
+		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+			http.NotFound(w, r)
+		}))
```
Comment (toshipp) [inline runners/metrics_client_test.go:42]: It can be more simplified as `httptest.NewServer(http.HandlerFunc(http.NotFound))`

**Review by toshipp — CHANGES_REQUESTED** [review]

File: runners/metrics_client_test.go (hunk 10 above)
Comment (bells17) [reply runners/metrics_client_test.go]: fixed it.

**Review by toshipp — APPROVED** [review]
LGTM

**Review by llamerada-jp — APPROVED** [review]
LGTM

**Review by satoru-takeuchi — APPROVED** [review]
