### PR TITLE
Extend metrics to include pvc name

### LINKED ISSUE #90: Add (or expand metric) to include information on volume that has been resized
In addition to all of the `*_total` metrics that are included, it would be useful to have individual metrics for specific volumes to be able to gather information on how many times a specific volume has been resized or has failed to resize. So rather than just seeing that we have X number of resized volumes over a period of time, we can see that volume-xyz has been resized X times over a period of time (which would help us potentially identify some other issue or tell us that we should ensure we have enough storage to cover growth, etc.)

### PR DESCRIPTION
**Pull request by tylerauerbeck**
Adds PersistentVolumeClaim name to appropriate metrics. Before adding too many additional labels, wanted to get feedback on if this was an appropriate approach.

resolves #90

### CODE REVIEW

File: metrics/resizer.go [hunk 1]
```diff
@@ -42,42 +42,42 @@ func (a *resizerLoopSecondsTotalAdapter) Add(value float64) {
...
 }
 
 var (
-	resizerSuccessResizeTotal = prometheus.NewCounter(prometheus.CounterOpts{
+	resizerSuccessResizeTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
 		Namespace: MetricsNamespace,
 		Name:      ResizerSuccessResizeTotalKey,
-		Help:      "counter that indicates how many volume expansion processing resizes succeed.",
-	})
+		Help:      "counter that indicates how m any volume expansion processing resized succeed.",
```
Comment (satoru-takeuchi) [inline metrics/resizer.go:56]:
```suggestion
		Help:      "counter that indicates how m any volume expansion processing resized succeed.",
```
```suggestion
		Help:      "counter that indicates how many volume expansion processing resized succeed.",
```

**Comment by satoru-takeuchi** [comment]
> wanted to get feedback on if this was an appropriate approach.

This change looks good to me. @toshipp , any comments?

**Review by toshipp — COMMENTED** [review]
Although this breaks backward compatibility, we will be able to bump the major version up, so we can approve it.

Because PVC is a namespace resource, I recommend adding a label to describe a namespace where PVC exists.

**Comment by tylerauerbeck** [comment]
@toshipp No problem. Added PVC namespace as a label and took this PR out of draft. Let me know if there's anything else you'd like to see.

File: metrics/resizer.go [hunk 2]
```diff
@@ -18,19 +18,19 @@ func init() {
...
 
 type resizerSuccessResizeTotalAdapter struct {
-	metric prometheus.Counter
+	metric prometheus.CounterVec
 }
 
-func (a *resizerSuccessResizeTotalAdapter) Increment() {
-	a.metric.Inc()
+func (a *resizerSuccessResizeTotalAdapter) Increment(pvcname string, pvcns string) {
+	a.metric.With(prometheus.Labels{"persistentvolumeclaim": pvcname, "persistentvolumeclaimnamespace": pvcns}).Inc()
```
Comment (toshipp) [inline metrics/resizer.go:25]: We are using kube-state-metrics internally. It exposes `kube_persistentvolumeclaim_info` metric that uses the `namespace` label to describe where the PVC exists. I think it is better to use it because it is easy to join by promql.
https://github.com/kubernetes/kube-state-metrics/blob/master/docs/persistentvolumeclaim-metrics.md

Comment (tylerauerbeck) [reply metrics/resizer.go:25]: So just to confirm, you would rather see the label be namespace rather than persistentvolumeclaimnamespace? I'm perfectly fine with that but didn't know if that would be an issue due to namespace already being used today:

ex:
```
pvcautoresizer_success_resize_total{container="pvc-autoresizer", endpoint="metrics", instance="1.2.3.4:8080", job="pvc-autoresizer/pvc-autoresizer", namespace="pvc-autoresizer", pod="pvc-autoresizer-controller-84c96b8f9d-85pqd"}
```

If you're fine with overwriting that current value, I can get this updated pretty quickly.

Comment (toshipp) [reply metrics/resizer.go:25]: I think it is fine. The namespace label is assigned by prometheus, and we can manage which one is used by `honor_labels` prometheus configuration.

**Review by toshipp — APPROVED** [review]
LGTM

**Review by satoru-takeuchi — APPROVED** [review]
